global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Messaging;
global using CommunityToolkit.Mvvm.Messaging.Messages;
global using Microsoft.Extensions.Logging;
global using OpenCvSharp;
global using System.Reactive.Linq;
global using System.Windows.Controls;
global using ZLogger;
global using CommunityToolkit.Mvvm.Input;